### ISSUE TITLE
Prepending the zimrc file disregarded relevant backslashes and following linebreaks

### ISSUE THREAD

**Issue by naibaf0** [zimfw/install#3]
When installing the setup via `curl -fsSL https://raw.githubusercontent.com/zimfw/install/develop/install.zsh | zsh` in the prepended code the backslashes in `.zimrc` in line 9-12 were missing, but the spaces from indentation were still there, so it looked a bit odd in the file :)
```
zstyle ':zim' modules     directory environment git git-info history input utility     steeef     zsh-completions completion     zsh-autosuggestions zsh-syntax-highlighting history-substring-search
```

**Comment by ericbn** [comment]
Thanks for reporting this, I'll check it on the next update.
